name       : python-jedi
version    : 0.12.1
release    : 4
source     :
    - https://github.com/davidhalter/jedi/archive/v0.12.1.tar.gz : 06adf7f28e25cb6bf5f2bce19307199833bd9bedae7dd61e3e8c5fc7a74eb647
license    : MIT
component  : programming.python
summary    : An autocompletion tool for Python that can be used for text editors.
description: |
    An autocompletion tool for Python that can be used for text editors.
builddeps  :
    - python-setuptools
rundeps    :
    - python-parso
build      : |
    %python_setup
install    : |
    %python_install
