name       : python-jedi
version    : 0.15.1
release    : 6
source     :
    - git|https://github.com/davidhalter/jedi.git : v0.15.1
license    : MIT
component  : programming.python
summary    : An autocompletion tool for Python that can be used for text editors.
description: |
    An autocompletion tool for Python that can be used for text editors.
builddeps  :
    - python-parso
    - python-pytest
    - python-setuptools
rundeps    :
    - python-parso
build      : |
    %python_setup
install    : |
    %python_install
check      : |
    %python_test pytest -k 'not test_file_path_completions'
