name       : python-jedi
version    : 0.10.2
release    : 1
source     :
    - https://github.com/davidhalter/jedi/archive/v0.10.2.tar.gz : 570aced88bc9ac34d8fa91d3db6de834f45c8adaac3f7fc1a1e9e08e19491acb
license    : 
    - MIT
    - Python-2.0
component  : programming.python
summary    : An autocompletion tool for Python that can be used for text editors.
description: |
    An autocompletion tool for Python that can be used for text editors.
build      : |
    %python_setup
install    : |
    %python_install
