name       : python-jedi
version    : 0.11.1
release    : 3
source     :
    - https://github.com/davidhalter/jedi/archive/v0.11.1.tar.gz : 748cdbac613a7659b1e83cc3b705f9f811580135cc690d16dafcbf8cabd4932f
license    : MIT
component  : programming.python
summary    : An autocompletion tool for Python that can be used for text editors.
description: |
    An autocompletion tool for Python that can be used for text editors.
builddeps  :
    - python-setuptools
rundeps    :
    - python-parso
build      : |
    %python_setup
install    : |
    %python_install
