name       : python-jedi
version    : 0.11.0
release    : 2
source     :
    - https://github.com/davidhalter/jedi/archive/v0.11.0.tar.gz : 0c4e80651d3441178628e4b0998225b9c9ed658abc599845e7fce741894d4a0f
license    : MIT
component  : programming.python
summary    : An autocompletion tool for Python that can be used for text editors.
description: |
    An autocompletion tool for Python that can be used for text editors.
builddeps  :
    - python-setuptools
rundeps    :
    - python-parso
build      : |
    %python_setup
install    : |
    %python_install
